import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {flex: 1, alignItems: 'center', backgroundColor: 'white'},
  loaderStyle: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  profileImg: {
    borderWidth: 0.9,
    borderColor: 'grey',
    width: 55,
    height: 55,
    borderRadius: 55 / 2,
  },
  titleTxt: {
    fontFamily: 'RobotoSlab-Bold',
    color: 'black',
    fontWeight: '600',
    fontSize: 15,
  },
  subTxt: {
    fontFamily: 'RobotoSlab-Bold',
    color: 'grey',
    fontWeight: '400',
    fontSize: 15,
  },
  subContainers: {
    paddingHorizontal: '8%',
    marginTop: 18,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ecf5fb',
    height: 52,
  },
  userNmeStyle: {
    fontFamily: 'RobotoSlab-Bold',
    alignSelf: 'center',
    fontWeight: '600',
    color: 'black',
    fontSize: 24,
    marginBottom: '8%',
  },
  editImgStyle: {borderRadius: 100 / 2, width: 100, height: 100},
  usrnmeContainer: {
    alignItems: 'center',
    height: 55,
    width: 55,
    borderRadius: 55 / 2,
    justifyContent: 'center',
  },
  uploadTxt: {
    fontFamily: 'RobotoSlab-Bold',
    fontSize: 16,
    color: '#0000ff',
    marginTop: 10,
  },

  scrolViewStyle: {
    width: '90%',
    padding: '2%',
    borderRadius: 33,
    borderWidth: 0.2,
    borderColor: 'black',
  },
  ediTxt: {
    fontFamily: 'RobotoSlab-Bold',
    marginLeft: '2%',
    marginTop: '7%',
    color: 'black',
    width: '55%',
    fontWeight: '600',
    fontSize: 29,
    marginBottom: 3,
  },
  prfileTxt: {
    marginLeft: '2%',
    fontWeight: '600',
    color: 'black',
    width: '55%',
    fontSize: 27,
    marginBottom: '10%',
    fontFamily: 'RobotoSlab-Bold',
  },
  imgContainer: {
    marginBottom: '6%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  emtyContainer: {
    alignItems: 'center',
    height: 55,
    width: 55,
    borderRadius: 55 / 2,
    justifyContent: 'center',
  },
  imgSubContainer: {
    alignItems: 'center',
    width: 115,
    height: 115,
    borderRadius: 115 / 2,
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'grey',
  },
  backArrow: {marginTop: '2%', marginLeft: '2%'},
});
