export default Constraints = {
  ABOUT_US_TITLE: 'About Us',
  WHO_WE_ARE: 'Who We Are?',
  WHAT_WE_DO: 'What We Do?',
  HOW_WE_DO: 'How We Do It – Technician ?',
  MOBILE_NUMBER: 'Mobile Number',
  MOBILE_NUMBER_Detail: 'We need to send OTP to authenticate your number',
  NEXT_BTN: 'Next',
  PERSONAL_DETAILS_TITLE: 'Personal Details',
  DONE_BTN: 'Done',
  SUBMIT_BTN: 'Submit',
  DID_RECEIVE_CODE: "Didn't receive code?",
  OTP: 'OTP',
  ENTER_OTP: 'Please enter the OTP send to your Mobile number',
  RESEND: 'Resend',
  WELCOME: 'Welcome',
  TO: 'to',
  MR_FIX: 'Mr.Fix',
  HELPING_HAND: 'Need a helping hand today ?',
  COMING_SOON: 'Coming Soon',
  OK: 'ok',
  ORDER_PLACED: ' Order Placed Successfully',
  ADD: 'Add',
  TRY_AGAIN: 'Try Again',
  NETWORK_CONNECTIVITY_ONE: 'Your requested action could not be completed',
  NETWORK_CONNECTIVITY: ' due to connectivity issues',
  NETWORK_ERROR: 'Network Error',
  WE_FIX_IT_RIGHT: 'We are fix it right',
  SCHEDULE_subTitle: 'Please select prefered visiting time',
  SCHEDULE: 'Schedule',
  CHECKOUT: 'CheckOut',
  EDIT: 'My',
  PROFILE: 'Profile',
  UPLOADING: 'Uplaoding...',
  NAME: 'Name',
  CONTACT: 'Contact',
  EMAIL_ADDRESS: 'Email Adress',
  PRIVACY_POLICY: 'Privacy Policy',
  MR_FIX_PRIVACY_POLICY: 'M.Fix Privacy Policy',
  CUSTOMER_VENDOR: 'Customer & Vendor Relations',
  CHOOSE_FROM_LISTING: 'Choose from Listing',
  SEARCH: 'Search...',
  HOME_SERVICES: 'Home Services',
  PERSONAL_SERVICES: 'Personal Services',
  ADD_TO_CART: 'Add to Cart',
  DONE: 'Done',
  RATE_RIDER: 'Rate',
};
